import java.awt.Font;
import java.util.Arrays;

/**
 *
 * @author adamv
 */
public class ThreeDTicTacToe extends javax.swing.JFrame {
    
   int turn = 1;
   char[][] board1 = new char[3][3];
    
   TicTacToeLogic ttt = new TicTacToeLogic();
   
   

    
    private void Action(javax.swing.JButton x, int i, int j,char [][] board)
    {
        boolean isOccupied = false;
        x.setFont(new Font("Serif", Font.PLAIN, 28));
        jButton1.setFont(new Font("Serif", Font.PLAIN, 28));
        
       
        if(turn == 1)
        {
        isOccupied = true;
        x.setText("X");
        board[i][j] = 'X';
       jButton1.setText("Player O pick a spot");
        turn = 2;
        }
        else if(turn == 2 && isOccupied == false)
        {
           isOccupied = true;
            x.setText("O");
            board[i][j] = 'O';
            jButton1.setText("Player X pick a spot");
            turn = 3;
        }
        else if(turn == 3 && isOccupied == false)
        {
         isOccupied = true;
         x.setText("X");
         board[i][j] = 'X';
         jButton1.setText("Player O pick a spot");
         turn = 4;
        }
        else if(turn == 4 && isOccupied == false)
        {
            isOccupied = true;
            x.setText("O");
            board[i][j] = 'O';
           jButton1.setText("Player X pick a spot");
            turn = 5;
        }
         else if(turn == 5 && isOccupied == false)
        {
         isOccupied = true;
         x.setText("X");
         board[i][j] = 'X';
         //check winner
         if(ttt.isSolved(board))
         {
             jButton1.setText("Winner is " + ttt.getWinner());
             jLabel1.setText("Click Below to Go Again");
             turn = 10;
         }
         else
         {
            jButton1.setText("Player O pick a spot");
            turn = 6;
         }
        }
         else if(turn == 6 && isOccupied == false)
        {
            isOccupied = true;
            x.setText("O");
            board[i][j] = 'O';
         
         if(ttt.isSolved(board))
         {
             jButton1.setText("Winner is " + ttt.getWinner());
             jLabel1.setText("Click Below to Go Again");
             turn = 10;
         }
         else
         {
            jButton1.setText("Player X pick a spot");
            turn = 7;
         }
        }
         else if(turn == 7 && isOccupied == false)
        {
         isOccupied = true;
         x.setText("X");
         board[i][j] = 'X';
         
         if(ttt.isSolved(board))
         {
             jButton1.setText("Winner is " + ttt.getWinner());
             jLabel1.setText("Click Below to Go Again");
             turn = 10;
         }
         else
         {
         jButton1.setText("Player O pick a spot");
         turn = 8;
         }
        }
         else if(turn == 8 && isOccupied == false)
        {
            isOccupied = true;
            x.setText("O");
            board[i][j] = 'O';
         if(ttt.isSolved(board))
         {
            jButton1.setText("Winner is " + ttt.getWinner());
            jLabel1.setText("Click Below to Go Again");
             turn = 10;
         }
         else
         {
            jButton1.setText("Player X pick a spot");
            turn = 9;
         }
        }
        else if(turn == 9 && isOccupied == false)
        {
         isOccupied = true;
         x.setText("X");
         board[i][j] = 'X';
         if(ttt.isSolved(board))
         {
             jButton1.setText("Winner is " + ttt.getWinner());
             jLabel1.setText("Click Below to Go Again");
             turn = 10;
         }
         else
         {
           jButton1.setText("DRAW!!!");
           jLabel1.setText("Click Below to Go Again");
            turn = 10;  
         }
        }
    }

    /**
     * Creates new form ThreeDTicTacToe
     */
    public ThreeDTicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Jlabel = new javax.swing.JLabel();
        ZeroZero = new javax.swing.JButton();
        ZeroOne = new javax.swing.JButton();
        ZeroTwo = new javax.swing.JButton();
        OneZero = new javax.swing.JButton();
        OneOne = new javax.swing.JButton();
        OneTwo = new javax.swing.JButton();
        TwoZero = new javax.swing.JButton();
        TwoOne = new javax.swing.JButton();
        TwoTwo = new javax.swing.JButton();
        GoAgain = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jlabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Jlabel.setText("TicTacToe");

        ZeroZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroZeroActionPerformed(evt);
            }
        });

        ZeroOne.setToolTipText("");
        ZeroOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroOneActionPerformed(evt);
            }
        });

        ZeroTwo.setToolTipText("");
        ZeroTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroTwoActionPerformed(evt);
            }
        });

        OneZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneZeroActionPerformed(evt);
            }
        });

        OneOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneOneActionPerformed(evt);
            }
        });

        OneTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneTwoActionPerformed(evt);
            }
        });

        TwoZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoZeroActionPerformed(evt);
            }
        });

        TwoOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoOneActionPerformed(evt);
            }
        });

        TwoTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoTwoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Player X pick a Spot");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("GAME Instructions");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(Jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(GoAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(TwoZero, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(69, 69, 69)
                                            .addComponent(TwoOne, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(OneZero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ZeroZero, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                            .addGap(70, 70, 70)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(ZeroOne, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                                .addComponent(OneOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ZeroTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TwoTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(OneTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ZeroTwo, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(ZeroZero, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(ZeroOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OneZero, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(OneOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OneTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TwoZero, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(TwoOne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TwoTwo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(GoAgain)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );

        pack();
    }// </editor-fold>                        

    private void ZeroZeroActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
      
        Action(ZeroZero,0,0,board1);
        
        
    }                                        

    private void ZeroOneActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
      
         Action(ZeroOne,0,1,board1);
        
    }                                       

    private void ZeroTwoActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
   
        Action(ZeroTwo,0,2,board1);
     
    }                                       

    private void OneZeroActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
     
        Action(OneZero,1,0,board1);
       
    }                                       

    private void OneOneActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    
        Action(OneOne,1,1,board1);
       
    }                                      

    private void OneTwoActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
  
        Action(OneTwo,1,2,board1);
    }                                      
   
    private void TwoZeroActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
     
        Action(TwoZero,2,0,board1);
      
    }                                       

    private void TwoOneActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
     
        Action(TwoOne,2,1,board1);
       
    }                                      

    private void TwoTwoActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
       
        
        Action(TwoTwo,2,2,board1);
        
    }                                      

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        if(turn == 10)
        {
            dispose();
            String [] args = null;
            main(args);
           
        }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThreeDTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThreeDTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThreeDTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThreeDTicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThreeDTicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel GoAgain;
    private javax.swing.JLabel Jlabel;
    private javax.swing.JButton OneOne;
    private javax.swing.JButton OneTwo;
    private javax.swing.JButton OneZero;
    private javax.swing.JButton TwoOne;
    private javax.swing.JButton TwoTwo;
    private javax.swing.JButton TwoZero;
    private javax.swing.JButton ZeroOne;
    private javax.swing.JButton ZeroTwo;
    private javax.swing.JButton ZeroZero;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}
